begin;

with incoming_departments(id, name, sort_order, status) as (
  values
    ('c01dddc9-850f-f2c4-509a-8dc7300fa9f8', 'Gerencia General', 1, 'active'),
    ('4a7cba7c-0bc9-4e3f-0565-789fc142f5c3', 'Administrativo y Financiero', 2, 'active'),
    ('faf4ee37-94ac-ea96-8fb6-d4758cd23b37', 'Talento Humano', 3, 'active'),
    ('ddaafc7d-fc37-7366-ea9d-8ac98f55a8eb', 'Cumplimiento', 4, 'active'),
    ('aef80bca-70e1-c52a-cb8e-0bbe863e8d57', 'Legal', 5, 'active'),
    ('254d317f-7158-3abd-73f3-b7e59ffc7b1b', 'Negocios y Alianzas', 6, 'active'),
    ('60dad368-8b4f-0cda-b58a-05f64297e127', 'Producto', 7, 'active'),
    ('5f24a937-4c2d-9e48-5177-505a7e421dd8', 'Operaciones', 8, 'active'),
    ('5aac7eaf-73dc-79fa-487d-7c028585a71a', 'Marketing', 9, 'active'),
    ('a97ff9b1-a60a-d0b1-f702-19bb8670dd41', 'Comercial', 10, 'active'),
    ('2a19fed1-9470-3b6f-495f-1440232e6c50', 'Servicio y Soporte al Cliente', 11, 'active'),
    ('b2490fc8-33bf-5afc-4478-0c14f0cc354b', 'Desarrollo', 12, 'active'),
    ('68b7e2a1-7020-8ae4-b90a-92455b895b56', 'Seguridad de la Información', 13, 'active'),
    ('f0c29169-d081-e762-48bd-3174768dbc2f', 'Tecnología e Información', 14, 'active')
)
insert into public.departments (id, name, sort_order, status, updated_at)
select id::uuid, name, sort_order, status, now()
from incoming_departments
on conflict (name) do update
set sort_order = excluded.sort_order,
    status = 'active',
    updated_at = now();

update public.departments
set status = 'inactive',
    updated_at = now()
where lower(name) not in ('gerencia general', 'administrativo y financiero', 'talento humano', 'cumplimiento', 'legal', 'negocios y alianzas', 'producto', 'operaciones', 'marketing', 'comercial', 'servicio y soporte al cliente', 'desarrollo', 'seguridad de la información', 'tecnología e información');

with incoming_people(
  id,
  full_name,
  role,
  email,
  department_name,
  status,
  department_sort_order,
  hierarchy_order,
  hierarchy_level,
  subarea,
  group_name,
  global_order,
  group_order,
  source_person_id,
  source_parent_id,
  source_row,
  source_pages,
  match_status,
  match_score,
  email_source,
  email_status
) as (
  values
    ('d1823f9b-305e-6891-47e5-904db6dcac00', 'Juan David Rúa', 'CEO', 'juandavid@epayco.com', 'Gerencia General', 'active', 1, 1, 'Dirección General', 'Gerencia General', 'Dirección General', 1, 1, 'per_juan_david_rua', null, '2', '2', 'OK', 96.5, 'JUAN DAVID RUA YARCE', 'OK'),
    ('b42e3b1f-d15f-b4db-7b80-5993ea3bff1a', 'Leidy Gil', 'Gerente de Gerencia General', 'leidy.gil@epayco.com', 'Gerencia General', 'active', 1, 2, 'Gerencia General', 'Gerencia General', 'Gerencia General', 2, 2, 'per_leidy_gil', 'per_juan_david_rua', '3', '2', 'OK', 91.3, 'LEIDY YULIANA GIL URIBE', 'OK'),
    ('3ae97191-d6f2-2f5a-4319-c01af3a1cdf6', 'Mauricio Gallego', 'Director Financiero', 'mauricio.bustamante@epayco.com', 'Administrativo y Financiero', 'active', 2, 2, 'Dirección Financiera', 'Administrativo y Financiero', 'Dirección Financiera', 3, 1, 'per_mauricio_gallego', 'per_juan_david_rua', '4', '3', 'OK', 53.7, 'Mauricio Gallego', 'OK'),
    ('ab8d85e2-6ade-ebbc-c467-462120732bec', 'Daniela Ochoa', 'Contadora', 'daniela.ochoa@epayco.com', 'Administrativo y Financiero', 'active', 2, 3, 'Contabilidad', 'Contabilidad', 'Contabilidad', 4, 2, 'per_daniela_ochoa', 'per_mauricio_gallego', '5', '3', 'OK', 96.2, 'DANIELA OCHOA MEJIA', 'OK'),
    ('54482231-8f43-5091-bedf-528db1172631', 'William Rúa', 'Líder de Tesorería', 'william.rua@epayco.com', 'Administrativo y Financiero', 'active', 2, 3, 'Tesorería', 'Tesorería', 'Tesorería', 5, 5, 'per_william_rua', 'per_mauricio_gallego', '6', '3', 'OK', 92.9, 'WILLIAM DARIO RUA YARCE', 'OK'),
    ('073af5e6-195c-c0e4-77cb-10da8cde2b2f', 'Jhonatan Giraldo', 'Líder Administrativo', 'jhonatan.giraldo@epayco.com', 'Administrativo y Financiero', 'active', 2, 3, 'Administrativo', 'Administrativo', 'Administrativo', 6, 7, 'per_jhonatan_giraldo', 'per_mauricio_gallego', '7', '3', 'OK', 92.3, 'JHONATAN ALEXANDER GIRALDO FERNANDEZ', 'OK'),
    ('e067385c-50c3-a2d7-2038-a5c0488022a6', 'Andres Moreno', 'Profesional Financiero', 'andres.moreno@epayco.com', 'Administrativo y Financiero', 'active', 2, 3, 'Financiero', 'Financiero', 'Financiero', 7, 11, 'per_andres_moreno', 'per_mauricio_gallego', '8', '3', 'OK', 93, 'ANDRES FELIPE MORENO TORRES', 'OK'),
    ('3b01dbec-5673-37f6-d146-200f3c12c453', 'Andrés Benavidez', 'Profesional Contable', 'andres.benavidez@epayco.com', 'Administrativo y Financiero', 'active', 2, 4, 'Contabilidad', 'Contabilidad', 'Contabilidad', 8, 3, 'per_andres_benavidez', 'per_daniela_ochoa', '9', '3', 'OK', 93.6, 'ANDRES CAMILO BENAVIDEZ GIRALDO', 'OK'),
    ('a5645ec6-6b8b-295c-c7eb-7a9d1368d220', 'Carolina Amariles', 'Analista Contable', 'carolina.rivera@epayco.com', 'Administrativo y Financiero', 'active', 2, 4, 'Contabilidad', 'Contabilidad', 'Contabilidad', 9, 4, 'per_carolina_amariles', 'per_daniela_ochoa', '10', '3', 'OK', 96.6, 'CAROLINA RIVERA AMARILES', 'OK'),
    ('00d6ad61-bafd-757c-9b90-e6d616fb1e55', 'Valentina de Arco', 'Analista de Pagos y Conciliaciones', 'valentina.torres@epayco.com', 'Administrativo y Financiero', 'active', 2, 4, 'Pagos y Conciliaciones', 'Tesorería', 'Pagos y Conciliaciones', 10, 6, 'per_valentina_de_arco', 'per_william_rua', '11', '3', 'OK', 96.6, 'VALENTINA DE ARCO TORRES', 'OK'),
    ('73c60846-f931-ebcb-3748-ac2d459f165c', 'Juan Esteban Carmona', 'Auxiliar Administrativo', 'juan.carmona@epayco.com', 'Administrativo y Financiero', 'active', 2, 4, 'Administrativo', 'Administrativo', 'Administrativo', 11, 8, 'per_juan_esteban_carmona', 'per_jhonatan_giraldo', '12', '3', 'OK', 96.7, 'JUAN ESTEBAN CARMONA ACEVEDO', 'OK'),
    ('4bb01c69-8e96-0c4f-58c5-86f5153523fa', 'Angela Mazo', 'Analista Administrativo', 'angela.mazo@epayco.com', 'Administrativo y Financiero', 'active', 2, 4, 'Administrativo', 'Administrativo', 'Administrativo', 12, 9, 'per_angela_mazo', 'per_jhonatan_giraldo', '13', '3', 'OK', 91.9, 'LUZ ANGELA MAZO BUSTAMANTE', 'OK'),
    ('985ad821-bc1a-58d8-b67f-432586326d15', 'Yuliana Parra', 'Auxiliar Administrativo', 'yuliana.parra@epayco.com', 'Administrativo y Financiero', 'active', 2, 4, 'Administrativo', 'Administrativo', 'Administrativo', 13, 10, 'per_yuliana_parra', 'per_jhonatan_giraldo', '14', '3', 'OK', 95.3, 'YULIANA PARRA CARMONA', 'OK'),
    ('aedf1d51-b0fd-bca9-c221-5a3c8d291709', 'Germán Alzate', 'Gerente de Talento Humano', 'german.alzate@epayco.com', 'Talento Humano', 'active', 3, 2, 'Gerencia Talento Humano', 'Talento Humano', 'Gerencia Talento Humano', 14, 1, 'per_german_alzate', 'per_juan_david_rua', '15', '4', 'OK', 92.7, 'GERMAN ALBERTO ALZATE FRANCO', 'OK'),
    ('a483ba28-c443-a82e-7d60-121ec46fbce0', 'Carolina Zapata', 'Analista de Selección', 'carolina.zapata@epayco.com', 'Talento Humano', 'active', 3, 4, 'Talento Humano', 'Talento Humano', 'Talento Humano', 15, 2, 'per_carolina_zapata', 'per_german_alzate', '16', '4', 'OK', 100, 'DIANA CAROLINA ZAPATA JIMENEZ', 'OK'),
    ('2559169a-d60f-bd45-333b-fe0982ce2a25', 'Xiomara Betancur', 'Auxiliar de Talento Humano', 'xiomara.betancur@epayco.com', 'Talento Humano', 'active', 3, 4, 'Talento Humano', 'Talento Humano', 'Talento Humano', 16, 3, 'per_xiomara_betancur', 'per_german_alzate', '17', '4', 'OK', 97.8, 'XIOMARA BETANCUR GIL', 'OK'),
    ('bc0034e1-8904-1769-387e-3d40813b81df', 'Gabriela Urdaneta', 'Analista de Bienestar y Formación', 'gabriela.urdaneta@epayco.com', 'Talento Humano', 'active', 3, 4, 'Talento Humano', 'Talento Humano', 'Talento Humano', 17, 4, 'per_gabriela_urdaneta', 'per_german_alzate', '18', '4', 'OK', 97, 'GABRIELA URDANETA DURAN', 'OK'),
    ('1197d87a-dd36-3d69-1e07-b8e39d22d935', 'Valentina Serna', 'Oficial de Cumplimiento', 'valentina.serna@epayco.com', 'Cumplimiento', 'active', 4, 2, 'Cumplimiento', 'Cumplimiento', 'Cumplimiento', 18, 1, 'per_valentina_serna', 'per_juan_david_rua', '19', '5', 'OK', 96.2, 'VALENTINA SERNA FLOREZ', 'OK'),
    ('81b364b9-6b07-babc-2bfc-fc1647e38548', 'Santiago Cobaleda', 'Analista de Cumplimiento', 'santiago.cobaleda@epayco.com', 'Cumplimiento', 'active', 4, 4, 'Cumplimiento', 'Cumplimiento', 'Cumplimiento', 19, 2, 'per_santiago_cobaleda', 'per_valentina_serna', '20', '5', 'OK', 95.8, 'SANTIAGO COBALEDA MONSALVE', 'OK'),
    ('f3e5d2bc-8ac9-d8cf-1c72-daf30801be63', 'Laura Madrigal', 'Directora Jurídica', 'laura.madrigal@epayco.com', 'Legal', 'active', 5, 2, 'Jurídica', 'Legal', 'Jurídica', 20, 1, 'per_laura_madrigal', 'per_juan_david_rua', '21', '6', 'OK', 95.6, 'LAURA MADRIGAL HERRERA', 'OK'),
    ('ba3e4fc5-4f21-d7fe-5950-a58238a8d68b', 'Daniel Valencia', 'Abogado', 'daniel.valencia@epayco.com', 'Legal', 'active', 5, 4, 'Jurídica', 'Legal', 'Jurídica', 21, 2, 'per_daniel_valencia', 'per_laura_madrigal', '22', '6', 'OK', 93.3, 'DANIEL FELIPE VALENCIA VASQUEZ', 'OK'),
    ('ff082cf8-8419-8310-bc3e-91531ca8bd9f', 'Diana Gonzalez', 'Gerente de Negocios y Alianzas', 'diana.gonzalez@epayco.com', 'Negocios y Alianzas', 'active', 6, 2, 'Negocios y Alianzas', 'Negocios y Alianzas', 'Negocios y Alianzas', 22, 1, 'per_diana_gonzalez', 'per_juan_david_rua', '23', '7', 'OK', 93.7, 'DIANA MELISA GONZALEZ MEJIA', 'OK'),
    ('7dac7838-bdf3-285b-e914-92d67098f013', 'Ainiri Vargas', 'Líder UX/UI', 'ainiri.vargas@epayco.com', 'Producto', 'active', 7, 3, 'UX/UI', 'Diseñadores UX/UI', 'UX/UI', 23, 1, 'per_ainiri_vargas', 'per_david_marroquin', '24', '8', 'OK', 92.7, 'AINIRI VIRGINIA VARGAS GOZZO', 'OK'),
    ('2bb26743-f8da-1f6a-4e9a-103584ba598f', 'David Marroquín', 'Líder de Producto', 'david.marroquin@epayco.com', 'Producto', 'active', 7, 3, 'Producto', 'Analistas de Producto / Especialistas de Producto', 'Producto', 24, 10, 'per_david_marroquin', 'per_juan_david_rua', '25', '9, 10', 'OK', 93, 'DAVID FERNANDO MARROQUIN VARGAS', 'OK'),
    ('37eab69b-bdbf-7bf5-135a-edf714998929', 'Katherin Ruíz', 'Analista UX/UI', 'katherin.ruiz@epayco.com', 'Producto', 'active', 7, 4, 'UX/UI', 'Diseñadores UX/UI', 'UX/UI', 25, 2, 'per_katherin_ruiz', 'per_ainiri_vargas', '26', '8', 'OK', 93.7, 'KATHERIN HELENA RUIZ MAGO', 'OK'),
    ('a1e5ab89-b66e-421d-dfc5-5131e9bd3bfc', 'Yeimy Espinosa', 'Analista UX/UI', 'yeimy.espinosa@epayco.com', 'Producto', 'active', 7, 4, 'UX/UI', 'Diseñadores UX/UI', 'UX/UI', 26, 3, 'per_yeimy_espinosa', 'per_ainiri_vargas', '27', '8', 'OK', 92.7, 'YEIMY JASNEIDY ESPINOSA TORRES', 'OK'),
    ('8793b87a-53c3-10d3-d5f2-a10c82e11ff7', 'Sara Calle', 'Analista UX/UI', 'melissa.calle@epayco.com', 'Producto', 'active', 7, 4, 'UX/UI', 'Diseñadores UX/UI', 'UX/UI', 27, 4, 'per_sara_calle', 'per_ainiri_vargas', '28', '8', 'OK', 92.1, 'SARA MELISSA CALLE LEON', 'OK'),
    ('ecf24c82-2278-7591-e85b-dbd5423ae2f1', 'Jose Meza', 'Analista UX/UI', 'jose.meza@epayco.com', 'Producto', 'active', 7, 4, 'UX/UI', 'Diseñadores UX/UI', 'UX/UI', 28, 5, 'per_jose_meza', 'per_ainiri_vargas', '29', '8', 'OK', 90.6, 'JOSE IGNACIO MEZA SANCHEZ', 'OK'),
    ('963a0c12-b1d0-63fd-fd13-519f49942d80', 'Daniela Areiza', 'Analista UX/UI', 'daniela.areiza@epayco.com', 'Producto', 'active', 7, 4, 'UX/UI', 'Diseñadores UX/UI', 'UX/UI', 29, 6, 'per_daniela_areiza', 'per_ainiri_vargas', '30', '8', 'OK', 95.6, 'DANIELA AREIZA LONDOÑO', 'OK'),
    ('49ac0f92-da01-d626-0d28-04614db4c9aa', 'Juan Camilo Acevedo', 'Product Owner', 'camilo.acevedo@epayco.com', 'Producto', 'active', 7, 4, 'Product Owners', 'Analistas de Producto', 'Product Owners', 30, 11, 'per_juan_camilo_acevedo', 'per_david_marroquin', '31', '9', 'OK', 97.3, 'JUAN CAMILO ACEVEDO PEREZ', 'OK'),
    ('c8c3dfe8-790f-cfe6-42d5-d0cfe620b86b', 'Sergio Monsalve', 'Product Owner', 'sergio.monsalve@epayco.com', 'Producto', 'active', 7, 4, 'Product Owners', 'Analistas de Producto', 'Product Owners', 31, 12, 'per_sergio_monsalve', 'per_david_marroquin', '32', '9', 'OK', 93.6, 'SERGIO ANDRES MONSALVE PIZANO', 'OK'),
    ('248efc61-01c1-c546-6d5f-0a7ec6400672', 'Bryan Andrade', 'Product Owner', 'bryan.andrade@epayco.com', 'Producto', 'active', 7, 4, 'Product Owners', 'Analistas de Producto', 'Product Owners', 32, 13, 'per_bryan_andrade', 'per_david_marroquin', '33', '9', 'OK', 95.3, 'BRYAN ANDRADE ANDRADE', 'OK'),
    ('855e8183-e7d7-f72f-624b-f3d401c4fc0d', 'Fabian Mesa', 'Product Owner', 'fabian.mesa@epayco.com', 'Producto', 'active', 7, 4, 'Product Owners', 'Analistas de Producto', 'Product Owners', 33, 14, 'per_fabian_mesa', 'per_david_marroquin', '34', '9', 'OK', 91.6, 'FABIAN ARLEY MESA HERNANDEZ', 'OK'),
    ('1ad2846c-9aa6-60d9-6c5e-6a5d19ea36d2', 'Alexandra Rúa', 'Especialista de Producto', 'alexandra.rua@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 34, 21, 'per_alexandra_rua', 'per_david_marroquin', '35', '10', 'OK', 94.4, 'ALEXANDRA RUA VELASQUEZ', 'OK'),
    ('244ecfca-983c-5695-e309-71fac9d36004', 'Daniela Jaramillo', 'Especialista de Producto', 'daniela.jaramillo@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 35, 22, 'per_daniela_jaramillo', 'per_david_marroquin', '36', '10', 'OK', 97, 'DANIELA JARAMILLO GOMEZ', 'OK'),
    ('e6e226bd-6e7b-6e6f-7448-df364d243fa6', 'Nicolas Donoso', 'Especialista de Producto', 'nicolas.donoso@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 36, 23, 'per_nicolas_donoso', 'per_david_marroquin', '37', '10', 'OK', 93, 'NICOLAS SANTIAGO DONOSO LOPEZ', 'OK'),
    ('7cc5c251-b844-4b57-bbbe-d1651fc6ad8e', 'Jennifer Hernández', 'Especialista de Producto', 'jennifer.hernandez@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 37, 24, 'per_jennifer_hernandez', 'per_david_marroquin', '38', '10', 'OK', 95.3, 'JENNIFER SUSEJ HERNANDEZ DIAZ', 'OK'),
    ('d2eab6f7-97a4-29ba-7962-fb859992e08e', 'Luis Felipe Vargas', 'Especialista de Producto', 'luis.vargas@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 38, 25, 'per_luis_felipe_vargas', 'per_david_marroquin', '39', '10', 'OK', 96.7, 'LUIS FELIPE VARGAS RIVERA', 'OK'),
    ('7bb3e20a-1b9e-017f-36bb-3ca771947584', 'Andrés Felipe Villamil', 'Especialista de Producto', 'andres.villamil@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 39, 26, 'per_andres_felipe_villamil', 'per_david_marroquin', '40', '10', 'OK', 96.9, 'ANDRES FELIPE VILLAMIL RAMIREZ', 'OK'),
    ('92908e75-71f2-04c9-e01c-01f433ac9909', 'Luisa Orozco', 'Especialista de Producto', 'luisa.orozco@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 40, 27, 'per_luisa_orozco', 'per_david_marroquin', '41', '10', 'OK', 92.3, 'LUISA FERNANDA OROZCO LOPEZ', 'OK'),
    ('fb3f7ef5-7677-6d87-0f5e-5bc28c0dc532', 'Wendy Reyes', 'Especialista de Producto', 'wendy.reyes@epayco.com', 'Producto', 'active', 7, 4, 'Especialistas de Producto', 'Especialistas de Producto', 'Especialistas de Producto', 41, 28, 'per_wendy_reyes', 'per_david_marroquin', '42', '10', 'OK', 92.2, 'WENDY CAMILA REYES PULIDO', 'OK'),
    ('331703bf-1c55-ae49-9293-e9c4ce1d6441', 'Alejandra Sanabria', 'Gerente', 'alejandra.sanabria@epayco.com', 'Operaciones', 'active', 8, 2, 'Gerencia Operaciones', 'Operaciones / Auxiliares de Operaciones', 'Gerencia Operaciones', 42, 1, 'per_alejandra_sanabria', 'per_juan_david_rua', '43', '11, 12', 'OK', 93.8, 'GILLIAN ALEJANDRA SANABRIA CUESTAS', 'OK'),
    ('f441d1aa-4f1d-b1fa-1115-68ede7efdc00', 'Camila Gallego', 'Analista de Monitoreo Transaccional', 'camila.gallego@epayco.com', 'Operaciones', 'active', 8, 4, 'Operaciones', 'Operaciones', 'Operaciones', 43, 2, 'per_camila_gallego', 'per_alejandra_sanabria', '44', '11', 'OK', 96, 'CAMILA GALLEGO FRANCO', 'OK'),
    ('491ef00b-5734-4c2f-6268-6756436698fd', 'Carolina Pulgarin', 'Analista de Prevención del Fraude', 'carolina.pulgarin@epayco.com', 'Operaciones', 'active', 8, 4, 'Operaciones', 'Operaciones', 'Operaciones', 44, 3, 'per_carolina_pulgarin', 'per_alejandra_sanabria', '45', '11', 'OK', 94.5, 'DIANA CAROLINA PULGARIN ZAPATA', 'OK'),
    ('4e2b344d-ed46-8fdb-b9a2-ad2e872b89ff', 'Alexander Urrego', 'Profesional de Riesgos', 'alexander.urrego@epayco.com', 'Operaciones', 'active', 8, 4, 'Operaciones', 'Operaciones', 'Operaciones', 45, 4, 'per_alexander_urrego', 'per_alejandra_sanabria', '46', '11', 'OK', 96, 'ALEXANDER URREGO CASTAÑO', 'OK'),
    ('15cf2b40-a1d9-b6d3-53d8-4080d8b55d99', 'Estefany Polo', 'Analista de Validación de Comercios', 'estefany.polo@epayco.com', 'Operaciones', 'active', 8, 4, 'Operaciones', 'Operaciones', 'Operaciones', 46, 5, 'per_estefany_polo', 'per_alejandra_sanabria', '47', '11', 'OK', 93, 'ESTEFANY JOHANA POLO RANGEL', 'OK'),
    ('e601e079-332e-60e8-f1ea-c446d961a68e', 'Vanesa Patiño', 'Auxiliar de Riesgo', 'vanesa.patino@epayco.com', 'Operaciones', 'active', 8, 4, 'Riesgo', 'Auxiliares de Operaciones', 'Riesgo', 47, 11, 'per_vanesa_patino', 'per_alejandra_sanabria', '48', '12', 'OK', 93.7, 'DAIANA VANESA PATIÑO CANO', 'OK'),
    ('d34f5110-2c8a-f9b1-a6e7-585246852257', 'Kelly Daza', 'Auxiliar de Operaciones', 'kelly.daza@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 48, 12, 'per_kelly_daza', 'per_alejandra_sanabria', '49', '12', 'OK', 90.5, 'KELLY JOHANNA DAZA JARAMILLO', 'OK'),
    ('6c6f6b5b-e82c-4402-13c8-ae448e852baf', 'Jenny Gomez', 'Auxiliar de Operaciones', 'jenny.gomez@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 49, 13, 'per_jenny_gomez', 'per_alejandra_sanabria', '50', '12', 'OK', 91.9, 'JENNY PAOLA GOMEZ QUINTERO', 'OK'),
    ('96addf4a-0c52-4680-5cf1-5bdbb270781b', 'Wendy Ortega', 'Auxiliar de Operaciones', 'wendy.ortega@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 50, 14, 'per_wendy_ortega', 'per_alejandra_sanabria', '51', '12', 'OK', 92.3, 'WENDY VANESA ORTEGA SARABIA', 'OK'),
    ('ae13fea8-6e80-d6a2-5a63-c70be34a8beb', 'Judy Carolina Tovar', 'Auxiliar de Operaciones', 'carolina.tovar@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 51, 15, 'per_judy_carolina_tovar', 'per_alejandra_sanabria', '52', '12', 'OK', 96.9, 'JUDY CAROLINA TOVAR TORRES', 'OK'),
    ('1077f53b-79ff-3c1b-6dd4-a526fdd9e7ee', 'Juan David Henao', 'Auxiliar de Operaciones', 'juan.henao@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 52, 16, 'per_juan_david_henao', 'per_alejandra_sanabria', '53', '12', 'OK', 100, 'JUAN DAVID HENAO', 'OK'),
    ('355615db-3019-3420-ab8f-b51788f9291d', 'Johan Orlas', 'Auxiliar de Operaciones', 'johan.orlas@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 53, 17, 'per_johan_orlas', 'per_alejandra_sanabria', '54', '12', 'OK', 92.9, 'JOHAN KARL ORLAS MUNERA', 'OK'),
    ('5ab23175-623c-452a-5c79-528c5a77f34e', 'Andres Julio', 'Auxiliar de Operaciones', 'andres.julio@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 54, 18, 'per_andres_julio', 'per_alejandra_sanabria', '55', '12', 'OK', 92.3, 'ARNALDO ANDRES JULIO YAGUNA', 'OK'),
    ('838a0bb2-8213-9de2-9844-f70cbd228c89', 'Juan Pablo Alvarez', 'Auxiliar de Operaciones', 'juan.alvarez@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 55, 19, 'per_juan_pablo_alvarez', 'per_alejandra_sanabria', '56', '12', 'OK', 96.4, 'JUAN PABLO ALVAREZ GALLEGO', 'OK'),
    ('0ecff9f2-ebaa-d656-4d26-51b009787d7a', 'Juan Camilo Morales', 'Auxiliar de Operaciones', 'camilo.morales@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 56, 20, 'per_juan_camilo_morales', 'per_alejandra_sanabria', '57', '12', 'OK', 97.3, 'JUAN CAMILO MORALES URIBE', 'OK'),
    ('2cfb93d3-19eb-6e59-2ba7-f70ddeca219f', 'Alejandra Villa', 'Auxiliar de Operaciones', 'alejandra.villa@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 57, 21, 'per_alejandra_villa', 'per_alejandra_sanabria', '58', '12', 'OK', 96.2, 'ALEJANDRA VILLA ROMERO', 'OK'),
    ('362a8432-e6e4-e2d6-938d-9a8bc9e87c02', 'Brandon Cervantes', 'Auxiliar de Operaciones', 'brandon.cervantes@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 58, 22, 'per_brandon_cervantes', 'per_alejandra_sanabria', '59', '12', 'OK', 93.9, 'BRANDON ALFREDO CERVANTES SUAREZ', 'OK'),
    ('f0b628d3-e60d-94d7-cbc4-daeb16527618', 'Laura Valeria de la Hoz', 'Auxiliar de Operaciones', 'valeria.londono@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 59, 23, 'per_laura_valeria_de_la_hoz', 'per_alejandra_sanabria', '60', '12', 'OK', 97, 'LAURA VALERIA DE LA HOZ LONDOÑO', 'OK'),
    ('4521ad81-0912-9669-ffae-f6fc004ff251', 'Nancy Correa', 'Auxiliar de Operaciones', 'nancy.correa@epayco.com', 'Operaciones', 'active', 8, 4, 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 'Auxiliares de Operaciones', 60, 24, 'per_nancy_correa', 'per_alejandra_sanabria', '61', '12', 'OK', 92.6, 'NANCY AMPARO CORREA ZAPATA', 'OK'),
    ('2eae7c4b-98ab-d65b-ecc0-b3b338988210', 'Karen Valbuena', 'Gerente de Marketing', 'karen.valbuena@epayco.com', 'Marketing', 'active', 9, 2, 'Gerencia Marketing', 'Marketing', 'Gerencia Marketing', 61, 1, 'per_karen_valbuena', 'per_juan_david_rua', '62', '13', 'OK', 92.7, 'KAREN YULIETH VALBUENA MONTOYA', 'OK'),
    ('49df6d09-853c-1e0b-72f2-a36500f4732b', 'Daniela Castellanos', 'Analista de Marketing', 'daniela.castellanos@epayco.com', 'Marketing', 'active', 9, 4, 'Marketing', 'Marketing', 'Marketing', 62, 2, 'per_daniela_castellanos', 'per_karen_valbuena', '63', '13', 'OK', 94.6, 'ANGIE DANIELA CASTELLANOS MONTOYA', 'OK'),
    ('f342d367-0c56-ac1a-b849-4db7004b8a69', 'Julian Tobón', 'Especialista de Email Marketing', 'julian.tobon@epayco.com', 'Marketing', 'active', 9, 4, 'Marketing', 'Marketing', 'Marketing', 63, 3, 'per_julian_tobon', 'per_karen_valbuena', '64', '13', 'OK', 96.6, 'JULIAN TOBON RUIZ', 'OK'),
    ('b6b3a6d1-e321-906e-e9b7-4eccaf6d4d9b', 'Alexis Herrera', 'Web Master', 'alexis.herrera@epayco.com', 'Marketing', 'active', 9, 4, 'Marketing', 'Marketing', 'Marketing', 64, 4, 'per_alexis_herrera', 'per_karen_valbuena', '65', '13', 'OK', 94.4, 'JAIME ALEXIS HERRERA RUIZ', 'OK'),
    ('fbdf6efa-32a4-4863-b607-926d8ceae775', 'Johana Franco', 'Diseñadora Gráfica', 'johana.franco@epayco.com', 'Marketing', 'active', 9, 4, 'Marketing', 'Marketing', 'Marketing', 65, 5, 'per_johana_franco', 'per_karen_valbuena', '66', '13', 'OK', 93.3, 'HEIDY JOHANA FRANCO ARANGO', 'OK'),
    ('5d0145a9-1b4e-190b-8fbd-b461f39ec85a', 'Jorge Ramirez', 'Director Comercial', 'jorge.ramirez@epayco.com', 'Comercial', 'active', 10, 2, 'Dirección Comercial', 'Área de Certificaciones', 'Dirección Comercial', 66, 1, 'per_jorge_ramirez', 'per_juan_david_rua', '67', '14', 'OK', 92.7, 'JORGE ALBERTO RAMIREZ CORTES', 'OK'),
    ('f534bbde-c68c-54dd-ec5c-04b1fcacca32', 'Luz Baena', 'Líder Comercial', 'luz.baena@epayco.com', 'Comercial', 'active', 10, 3, 'Líder Comercial', 'Área de Certificaciones', 'Líder Comercial', 67, 2, 'per_luz_baena', 'per_jorge_ramirez', '68', '14', 'OK', 90.9, 'LUZ ENITH BAENA CEBALLOS', 'OK'),
    ('2f900833-c350-3f34-6910-e96542fe0fce', 'Catherine Aguilar', 'Líder de Certificaciones', 'caguilar@epayco.com', 'Comercial', 'active', 10, 3, 'Certificaciones', 'Área de Certificaciones', 'Certificaciones', 68, 30, 'per_catherine_aguilar', 'per_jorge_ramirez', '69', '14', 'OK', 96.2, 'CATHERINE AGUILAR MONTOYA', 'OK'),
    ('fe2480ec-df15-a831-3a03-28e12cc0504f', 'Valentina Aguilar', 'Auxiliar Comercial', 'valentina.aguilar@epayco.com', 'Comercial', 'active', 10, 4, 'Auxiliares Comerciales', 'Área de Certificaciones', 'Auxiliares Comerciales', 69, 3, 'per_valentina_aguilar', 'per_luz_baena', '70', '14', 'OK', 96.2, 'VALENTINA AGUILAR MONTOYA', 'OK'),
    ('2820b3af-fc89-6c02-46ab-308d71946da6', 'Tatiana Giraldo', 'Auxiliar Comercial', 'tatiana.giraldo@epayco.com', 'Comercial', 'active', 10, 4, 'Auxiliares Comerciales', 'Área de Certificaciones', 'Auxiliares Comerciales', 70, 4, 'per_tatiana_giraldo', 'per_luz_baena', '71', '14', 'OK', 96.7, 'TATIANA GIRALDO CAÑAS', 'OK'),
    ('7b4b3645-ed71-8a36-9ac1-02dd629f164d', 'Jackeline Santafe', 'Auxiliar Comercial', 'jackeline.santafe@epayco.com', 'Comercial', 'active', 10, 4, 'Auxiliares Comerciales', 'Área de Certificaciones', 'Auxiliares Comerciales', 71, 5, 'per_jackeline_santafe', 'per_luz_baena', '72', '14', 'OK', 95.8, 'JACKELINE SANTAFE ARBOLEDA', 'OK'),
    ('66dfce34-071d-6178-42f2-8b7768a103da', 'Carolina Castaño', 'Auxiliar Comercial', 'carolina.castano@epayco.com', 'Comercial', 'active', 10, 4, 'Auxiliares Comerciales', 'Área de Certificaciones', 'Auxiliares Comerciales', 72, 6, 'per_carolina_castano', 'per_luz_baena', '73', '14', 'OK', 97.3, 'CAROLINA CASTAÑO MESA', 'OK'),
    ('59e4dbd5-fffb-353f-27ec-607731306500', 'Alejandra Taborda', 'Auxiliar Comercial', 'alejandra.taborda@epayco.com', 'Comercial', 'active', 10, 4, 'Auxiliares Comerciales', 'Área de Certificaciones', 'Auxiliares Comerciales', 73, 7, 'per_alejandra_taborda', 'per_luz_baena', '74', '14', 'OK', 94.8, 'DIANA ALEJANDRA TABORDA HENAO', 'OK'),
    ('59fe0e73-22cf-fa5b-ab0d-ee960307f555', 'Maria José Giraldo', 'Auxiliar Comercial', 'maria.giraldo@epayco.com', 'Comercial', 'active', 10, 4, 'Auxiliares Comerciales', 'Área de Certificaciones', 'Auxiliares Comerciales', 74, 8, 'per_maria_jose_giraldo', 'per_luz_baena', '75', '14', 'OK', 96.7, 'MARIA JOSE GIRALDO PINEDA', 'OK'),
    ('fb443ffd-788e-7ea8-c435-a5b0e1457f6f', 'Paola Castellanos', 'Asesor Comercial', 'paola.castellanos@epayco.com', 'Comercial', 'active', 10, 4, 'Asesores Comerciales', 'Área de Certificaciones', 'Asesores Comerciales', 75, 20, 'per_paola_castellanos', 'per_jorge_ramirez', '76', '14', 'OK', 93.6, 'VIVIANA PAOLA CASTELLANOS MONTOYA', 'OK'),
    ('4c690b25-8efe-04e4-0340-e0e2e1ae51a4', 'Mónica Martínez', 'Asesor Comercial', 'monica.martinez@epayco.com', 'Comercial', 'active', 10, 4, 'Asesores Comerciales', 'Área de Certificaciones', 'Asesores Comerciales', 76, 21, 'per_monica_martinez', 'per_jorge_ramirez', '77', '14', 'OK', 94, 'MONICA ANDREA MARTINEZ LOPEZ', 'OK'),
    ('06fd2e24-0446-076e-c5a1-c25b72746fb5', 'Daniela Arbelaez', 'Asesor Comercial', 'daniela.arbelaez@epayco.com', 'Comercial', 'active', 10, 4, 'Asesores Comerciales', 'Área de Certificaciones', 'Asesores Comerciales', 77, 22, 'per_daniela_arbelaez', 'per_jorge_ramirez', '78', '14', 'OK', 96, 'DANIELA ARBELAEZ PALACIO', 'OK'),
    ('c7149357-c858-77d0-4c30-73011795fa60', 'Daniela Gutiérrez', 'Analista de Certificaciones', 'daniela.gutierrez@epayco.com', 'Comercial', 'active', 10, 4, 'Analistas de Certificaciones', 'Área de Certificaciones', 'Analistas de Certificaciones', 78, 31, 'per_daniela_gutierrez', 'per_catherine_aguilar', '79', '14', 'OK', 93.1, 'DANIELA ALEJANDRA GUTIERREZ HIGINIO', 'OK'),
    ('e11308f1-4ab6-0307-5007-3a2edf18699e', 'Tatiana Torres', 'Analista de Certificaciones', 'leidy.torres@epayco.com', 'Comercial', 'active', 10, 4, 'Analistas de Certificaciones', 'Área de Certificaciones', 'Analistas de Certificaciones', 79, 32, 'per_tatiana_torres', 'per_catherine_aguilar', '80', '14', 'OK', 94.4, 'LEIDY TATIANA TORRES TORO', 'OK'),
    ('4feae45e-a8ec-1d1d-1597-7b3f8ad2015a', 'Durley Montoya', 'Analista de Certificaciones', 'durley.montoya@epayco.com', 'Comercial', 'active', 10, 4, 'Analistas de Certificaciones', 'Área de Certificaciones', 'Analistas de Certificaciones', 80, 33, 'per_durley_montoya', 'per_catherine_aguilar', '81', '14', 'OK', 96, 'DURLEY SULEMA MONTOYA', 'OK'),
    ('a5e57c43-5f72-4c4c-3f2b-ab2a4d3eccce', 'Claudia Osorno', 'Analista de Certificaciones', 'claudia.osorno@epayco.com', 'Comercial', 'active', 10, 4, 'Analistas de Certificaciones', 'Área de Certificaciones', 'Analistas de Certificaciones', 81, 34, 'per_claudia_osorno', 'per_catherine_aguilar', '82', '14', 'OK', 92.7, 'CLAUDIA PATRICIA OSORNO PATIÑO', 'OK'),
    ('383982df-93ac-38f8-9f77-325069ddd47c', 'Mónica Ramirez', 'Analista de Certificaciones', 'monica.ramirez@epayco.com', 'Comercial', 'active', 10, 4, 'Analistas de Certificaciones', 'Área de Certificaciones', 'Analistas de Certificaciones', 82, 35, 'per_monica_ramirez', 'per_catherine_aguilar', '83', '14', 'OK', 91.7, 'MONICA ALEXANDRA RAMIREZ ECHEVERRY', 'OK'),
    ('b960017e-03c2-fa72-8ed1-07634160cffc', 'Juan Diego Vargas', 'Líder de Servicio y Soporte al Cliente', 'diego.vargas@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 3, 'Liderazgo Servicio', 'Servicio y Soporte al Cliente / Soporte e Integraciones', 'Liderazgo Servicio', 83, 1, 'per_juan_diego_vargas', 'per_juan_david_rua', '84', '15, 16', 'OK', 96.6, 'JUAN DIEGO VARGAS POSADA', 'OK'),
    ('2b219794-f520-bbf4-13da-3e1480693750', 'Carolina Euse', 'Agente de Servicio y Soporte al Cliente', 'carolina.euse@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 84, 2, 'per_carolina_euse', 'per_juan_diego_vargas', '85', '15', 'OK', 94.9, 'CAROLINA EUSE MARTINEZ', 'OK'),
    ('cc086120-c200-8b91-c38c-10e23af49c66', 'Ma. Ángeles Mejía', 'Agente de Servicio y Soporte al Cliente', 'maria.mejia@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 85, 3, 'per_maria_angeles_mejia', 'per_juan_diego_vargas', '86', '15', 'OK', 94.6, 'MARIA DE LOS ANGELES MEJIA CORREA', 'OK'),
    ('73480306-1015-92e6-7fab-20383aec371a', 'Johan David Restrepo', 'Agente de Servicio y Soporte al Cliente', 'johan.restrepo@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 86, 4, 'per_johan_david_restrepo', 'per_juan_diego_vargas', '87', '15', 'OK', 96.7, 'JOHAN DAVID RESTREPO SANCHEZ', 'OK'),
    ('40336f6c-17f7-22cd-c1db-b62852056892', 'Luisa Ramirez', 'Agente de Servicio y Soporte al Cliente', 'luisa.ramirez@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 87, 5, 'per_luisa_ramirez', 'per_juan_diego_vargas', '88', '15', 'OK', 91.6, 'LUISA FERNANDA RAMIREZ HERNANDEZ', 'OK'),
    ('2770f344-c541-e96f-dbb7-6afbe8e40aa1', 'Carolina Villamil', 'Agente de Servicio y Soporte al Cliente', 'carolina.villamil@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 88, 6, 'per_carolina_villamil', 'per_juan_diego_vargas', '89', '15', 'OK', 93.3, 'ASTRID CAROLINA VILLAMIL HERNANDEZ', 'OK'),
    ('8f5e450f-d91b-815f-326d-e28729428266', 'Juan Esteban Santana', 'Agente de Servicio y Soporte al Cliente', 'juan.santana@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 89, 7, 'per_juan_esteban_santana', 'per_juan_diego_vargas', '90', '15', 'OK', 97, 'JUAN ESTEBAN SANTANA OBANDO', 'OK'),
    ('9ca8ae70-eece-a239-4a89-3da1bd0ae186', 'Mateo Jaramillo', 'Agente de Servicio y Soporte al Cliente', 'mateo.jaramillog@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 90, 8, 'per_mateo_jaramillo', 'per_juan_diego_vargas', '91', '15', 'OK', 95.8, 'MATEO JARAMILLO GRANADA', 'OK'),
    ('ebf5debf-07d3-f936-6d34-93acfa59e654', 'Jesus Gonzalez', 'Agente de Servicio y Soporte al Cliente', 'jesus.gonzalez@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agentes de Servicio y Soporte al Cliente', 'Servicio y Soporte al Cliente', 'Agentes de Servicio y Soporte al Cliente', 91, 9, 'per_jesus_gonzalez', 'per_juan_diego_vargas', '92', '15', 'OK', 93.7, 'JESUS DAVID GONZALEZ OSPINA', 'OK'),
    ('dfe36c3e-5da6-41dc-c60b-7dead6f3cc7c', 'Juan Felipe Herrera', 'Agente de Soporte e Integraciones', 'felipe.herrera@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agente de Soporte e Integraciones', 'Soporte e Integraciones', 'Agente de Soporte e Integraciones', 92, 21, 'per_juan_felipe_herrera', 'per_juan_diego_vargas', '93', '16', 'OK', 96.5, 'JUAN FELIPE HERRERA ACEVEDO', 'OK'),
    ('3895ab06-92fc-ab62-aa4b-cf7f0d4dfb90', 'Ma. Ángeles Abello', 'Agente de Soporte e Integraciones', 'maria.abello@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agente de Soporte e Integraciones', 'Soporte e Integraciones', 'Agente de Soporte e Integraciones', 93, 22, 'per_maria_angeles_abello', 'per_juan_diego_vargas', '94', '16', 'OK', 94.5, 'MARIA DE LOS ANGELES ABELLO TABORDA', 'OK'),
    ('a5c700d0-b825-6b76-58b1-63ec2840cb8d', 'Eliana Henao', 'Agente de Soporte e Integraciones', 'eliana.henao@epayco.com', 'Servicio y Soporte al Cliente', 'active', 11, 4, 'Agente de Soporte e Integraciones', 'Soporte e Integraciones', 'Agente de Soporte e Integraciones', 94, 23, 'per_eliana_henao', 'per_juan_diego_vargas', '95', '16', 'OK', 91.7, 'ELIANA MARCELA HENAO MARTINEZ', 'OK'),
    ('ace9c347-bd02-2abe-3c15-1f429d32c451', 'Daniel Quiroz', 'CTO', 'daniel.quiroz@epayco.com', 'Desarrollo', 'active', 12, 2, 'Backend / Fullstack y Profesionales / Desarrolladores', 'Desarrolladores Backend / Desarrolladores Fullstack y Profesionales / Desarrolladores', 'Backend / Fullstack y Profesionales / Desarrolladores', 95, 30, 'per_daniel_quiroz', 'per_juan_david_rua', '96', '19, 20, 21-22', 'OK', 93.3, 'JOSE DANIEL QUIROZ SANCHEZ', 'OK'),
    ('d5cf76d4-4988-b010-e8dc-781905e87a70', 'Paola Alzate', 'Líder QA', 'paola.alzate@epayco.com', 'Desarrollo', 'active', 12, 3, 'QA', 'QA', 'QA', 96, 1, 'per_paola_alzate', 'per_daniel_quiroz', '97', '17', 'OK', 92, 'PAOLA MARGARITA ALZATE LOPEZ', 'OK'),
    ('421dea9a-05c3-840f-9103-75dedfcf268b', 'Nixon Cardona', 'Líder de Proyectos', 'nixon.cardona@epayco.com', 'Desarrollo', 'active', 12, 3, 'Proyectos', 'Especialistas de Proyectos', 'Proyectos', 97, 10, 'per_nixon_cardona', 'per_daniel_quiroz', '98', '18', 'OK', 93, 'NIXON YESID CARDONA ALVAREZ', 'OK'),
    ('1302625d-dc1f-18ce-901d-99ec2f0844ba', 'Carlos Moreno', 'Analista QA', 'carlos.moreno@epayco.com', 'Desarrollo', 'active', 12, 4, 'QA', 'QA', 'QA', 98, 2, 'per_carlos_moreno', 'per_paola_alzate', '99', '17', 'OK', 93.7, 'CARLOS FERNEY MORENO RUIZ', 'OK'),
    ('70b8ee55-d858-6315-b594-41223cd63a3b', 'Neida Montoya', 'Analista QA', 'neida.montoya@epayco.com', 'Desarrollo', 'active', 12, 4, 'QA', 'QA', 'QA', 99, 3, 'per_neida_montoya', 'per_paola_alzate', '100', '17', 'OK', 92.4, 'NEIDA CRISTELA MONTOYA SIERRA', 'OK'),
    ('69ee85b4-e537-19e7-621c-f42c518666fa', 'Andrés Castañeda', 'Analista QA', 'andres.castaneda@epayco.com', 'Desarrollo', 'active', 12, 4, 'QA', 'QA', 'QA', 100, 4, 'per_andres_castaneda', 'per_paola_alzate', '101', '17', 'OK', 100, 'ANDRES FELIPE CASTAÑEDA CASTAÑEDA', 'OK'),
    ('4bb7d035-f85c-bc11-fd6e-30e162266057', 'Yonny Ospina', 'Analista QA', 'yonny.ospina@epayco.com', 'Desarrollo', 'active', 12, 4, 'QA', 'QA', 'QA', 101, 5, 'per_yonny_ospina', 'per_paola_alzate', '102', '17', 'OK', 91.7, 'YONNY ALEXANDER OSPINA OSPINA', 'OK'),
    ('a7706c49-fc84-99bc-b5b4-f410cf054c9b', 'Beatriz Monserrate', 'Analista QA', 'maria.monserrate@epayco.com', 'Desarrollo', 'active', 12, 4, 'QA', 'QA', 'QA', 102, 6, 'per_beatriz_monserrate', 'per_paola_alzate', '103', '17', 'OK', 94.4, 'MARIA BEATRIZ MONSERRATE JIMENEZ', 'OK'),
    ('e95dc2e5-615c-160b-c55b-6c6e5de1775c', 'Jaqueline Orozco', 'Auxiliar QA', 'jaqueline.orozco@epayco.com', 'Desarrollo', 'active', 12, 4, 'QA', 'QA', 'QA', 103, 7, 'per_jaqueline_orozco', 'per_paola_alzate', '104', '17', 'OK', 95.6, 'JAQUELINE OROZCO ARANZAZU', 'OK'),
    ('c14e3a7b-071b-d4be-3112-992fb9951e42', 'M. Alejandra Correa', 'Especialista de Proyectos', 'maria.correa@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 104, 11, 'per_maria_alejandra_correa', 'per_nixon_cardona', '105', '18', 'OK', 96.6, 'MARIA ALEJANDRA CORREA CESPEDES', 'OK'),
    ('16e66109-576a-5b6d-8e27-c45ba610e17d', 'Ma. Alejandra Naranjo', 'Especialista de Proyectos', 'maria.naranjo@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 105, 12, 'per_maria_alejandra_naranjo', 'per_nixon_cardona', '106', '18', 'OK', 97, 'MARIA ALEJANDRA NARANJO PALACIO', 'OK'),
    ('298f3a72-57be-47f1-8106-0253d84d32f0', 'Tatiana Betancurth', 'Especialista de Proyectos', 'tatiana.betancurth@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 106, 13, 'per_tatiana_betancurth', 'per_nixon_cardona', '107', '18', 'OK', 93.8, 'TATIANA ALEXANDRA BETANCURTH PAIBA', 'OK'),
    ('a1bd37ba-32d3-ba82-7e52-022a046bb04a', 'Olga Cespedes', 'Especialista de Proyectos', 'olga.cespedes@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 107, 14, 'per_olga_cespedes', 'per_nixon_cardona', '108', '18', 'OK', 92.7, 'OLGA LUCIA CESPEDES BUITRAGO', 'OK'),
    ('a5c39ea7-04f8-abd1-40a0-18fd4fa58dba', 'Valentina Moreno', 'Especialista de Proyectos', 'valentina.moreno@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 108, 15, 'per_valentina_moreno', 'per_nixon_cardona', '109', '18', 'OK', 97.3, 'VALENTINA MORENO TORO', 'OK'),
    ('5b65ec50-d5bb-1902-87ed-b595246e7610', 'Laura Perez', 'Especialista de Proyectos', 'laura.perez@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 109, 16, 'per_laura_perez', 'per_nixon_cardona', '110', '18', 'OK', 91.9, 'LAURA CRISTINA PEREZ LOPEZ', 'OK'),
    ('86d8ed79-b1f1-a574-5420-5be46d99625c', 'Luisa Momphotes', 'Especialista de Proyectos', 'luisa.momphotes@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 110, 17, 'per_luisa_momphotes', 'per_nixon_cardona', '111', '18', 'OK', 93.3, 'LUISA FERNANDA MOMPHOTES PARRA', 'OK'),
    ('2bfd9ba9-7c75-6cdb-d33e-35baf8499215', 'Andrés García', 'Especialista de Proyectos', 'andres.garcia@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 111, 18, 'per_andres_garcia', 'per_nixon_cardona', '112', '18', 'OK', 94.1, 'ANDRES FELIPE GARCIA RUA', 'OK'),
    ('1a673559-43bb-7183-deba-afcf02128969', 'Ma Alejandra Nieto', 'Especialista de Proyectos', 'alejandra.nieto@epayco.com', 'Desarrollo', 'active', 12, 4, 'Especialistas de Proyectos', 'Especialistas de Proyectos', 'Especialistas de Proyectos', 112, 19, 'per_maria_alejandra_nieto', 'per_nixon_cardona', '113', '18', 'OK', 96.8, 'MARIA ALEJANDRA NIETO GAVIRIA', 'OK'),
    ('a64b68ad-a068-bf57-1c64-9005e5e447c1', 'Carlos Duque', 'Desarrollador Backend', 'carlos.duque@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 114, 31, 'per_carlos_duque', 'per_daniel_quiroz', '114', '19', 'OK', 91.2, 'CARLOS ALEJANDRO DUQUE CORRALES', 'OK'),
    ('95448a93-8857-2f15-98d5-d40100b94faf', 'Ricardo Saldarriaga', 'Desarrollador Backend', 'ricardo.saldarriaga@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 115, 32, 'per_ricardo_saldarriaga', 'per_daniel_quiroz', '115', '19', 'OK', 94.9, 'JOSE RICARDO SALDARRIAGA ALVAREZ', 'OK'),
    ('f4f34749-2094-f781-cd4b-7b8549a9b417', 'Luis Fuentes', 'Desarrollador Backend', 'luis.fuentes@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 116, 33, 'per_luis_fuentes', 'per_daniel_quiroz', '116', '19', 'OK', 92.3, 'LUIS ALBERTO FUENTES AURAAD', 'OK'),
    ('87e3af6d-6a6a-33e0-2e71-cce9b7b14369', 'Juan Correa', 'Desarrollador Backend', 'juan.correa@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 117, 34, 'per_juan_correa', 'per_daniel_quiroz', '117', '19', 'OK', 92.9, 'JUAN FELIPE CORREA RIOS', 'OK'),
    ('4bc73486-4d11-eabf-5773-fb44c165e4c0', 'Jordan Cuadro', 'Desarrollador Backend', 'jordan.cuadro@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 118, 35, 'per_jordan_cuadro', 'per_daniel_quiroz', '118', '19', 'OK', 92.1, 'JORDAN JHONSSON CUADRO NEGRETE', 'OK'),
    ('c8fbbc9e-b72f-84ad-6cd7-72d15b539467', 'Wilfredo Sulbaran', 'Desarrollador Backend', 'wilfredo.sulbaran@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 119, 36, 'per_wilfredo_sulbaran', 'per_daniel_quiroz', '119', '19', 'OK', 93.6, 'WILFREDO ANTONIO SULBARAN NAVARRO', 'OK'),
    ('0043003d-fec5-0705-bf8f-0d8c7f6c1381', 'Dorian López', 'Desarrollador Backend', 'dorian.lopez@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 120, 37, 'per_dorian_lopez', 'per_daniel_quiroz', '120', '19', 'OK', 92.6, 'DORIAN ANDRES LOPEZ OROZCO', 'OK'),
    ('594e64fe-35a2-e508-9eb5-e51e07fb0b54', 'Nelson Lindarte', 'Desarrollador Backend', 'nelson.lindarte@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 121, 38, 'per_nelson_lindarte', 'per_daniel_quiroz', '121', '19', 'OK', 94, 'NELSON CAMILO LINDARTE ORTIZ', 'OK'),
    ('51da3d9c-1864-8b22-d831-d78a6bc7e8a2', 'Oscar Paz', 'Desarrollador Backend', 'oscar.paz@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 122, 39, 'per_oscar_paz', 'per_daniel_quiroz', '122', '19', 'OK', 90.6, 'OSCAR DARIO PAZ BENAVIDES', 'OK'),
    ('bb555524-248c-0741-c3ff-b6c29c1da4f1', 'Jose Chaverra', 'Desarrollador Backend', 'jose.chaverra@epayco.com', 'Desarrollo', 'active', 12, 4, 'Backend', 'Desarrolladores Backend', 'Backend', 123, 40, 'per_jose_chaverra', 'per_daniel_quiroz', '123', '19', 'OK', 93.3, 'JOSE DAVID CHAVERRA PELAEZ', 'OK'),
    ('4021f322-cabc-8cda-7941-6a834d46c601', 'Victor Cortés', 'Desarrollador', 'victor.cortes@epayco.com', 'Desarrollo', 'active', 12, 4, 'Fullstack y Profesionales', 'Desarrolladores Fullstack y Profesionales', 'Fullstack y Profesionales', 124, 51, 'per_victor_cortes', 'per_daniel_quiroz', '124', '20', 'OK', 93.7, 'VICTOR HUGO CORTES POSADA', 'OK'),
    ('f94e0a64-960c-023e-d565-85634ec91e04', 'Camilo Montoya', 'Desarrollador', 'camilo.montoya@epayco.com', 'Desarrollo', 'active', 12, 4, 'Fullstack y Profesionales', 'Desarrolladores Fullstack y Profesionales', 'Fullstack y Profesionales', 125, 52, 'per_camilo_montoya', 'per_daniel_quiroz', '125', '20', 'OK', 100, 'CAMILO ANDRES MONTOYA CASTAÑEDA', 'OK'),
    ('c23b96f6-3909-7975-1857-8331fdb1bec3', 'Juan García', 'Profesional de Desarrollo', 'juan.garcia@epayco.com', 'Desarrollo', 'active', 12, 4, 'Fullstack y Profesionales', 'Desarrolladores Fullstack y Profesionales', 'Fullstack y Profesionales', 126, 53, 'per_juan_garcia', 'per_daniel_quiroz', '126', '20', 'REVISAR', 100, 'JUAN ESTEBAN GARCIA VALENCIA', 'OK'),
    ('68d4f274-df71-6ab0-586a-490553aed59d', 'Nelson Valencia', 'Profesional de Desarrollo', 'nelson.valencia@epayco.com', 'Desarrollo', 'active', 12, 4, 'Fullstack y Profesionales', 'Desarrolladores Fullstack y Profesionales', 'Fullstack y Profesionales', 127, 54, 'per_nelson_valencia', 'per_daniel_quiroz', '127', '20', 'OK', 94, 'NELSON DAVID VALENCIA ALZATE', 'OK'),
    ('928f50f3-b18d-7672-fe49-190179d9d071', 'Brandon Granados', 'Desarrollador', 'sebastian.granados@epayco.com', 'Desarrollo', 'active', 12, 4, 'Fullstack y Profesionales', 'Desarrolladores Fullstack y Profesionales', 'Fullstack y Profesionales', 128, 55, 'per_brandon_granados', 'per_daniel_quiroz', '128', '20', 'OK', 91.9, 'BRANDON SEBASTIAN GRANADOS CASTIBLANCO', 'OK'),
    ('808ae43d-0782-1ccb-34e3-ac5c2c41a791', 'Jonathan Aguirre', 'Líder Técnico', 'jaguirre@epayco.com', 'Desarrollo', 'active', 12, 4, 'Desarrolladores', 'Desarrolladores', 'Desarrolladores', 129, 71, 'per_jonathan_aguirre', 'per_daniel_quiroz', '129', '21-22', 'OK', 96, 'JONATHAN AGUIRRE ESCOBAR', 'OK'),
    ('9a8ca712-47a3-c971-e426-f27468cda90b', 'Sergio Ríos', 'Líder Técnico', 'sergio.rios@epayco.com', 'Desarrollo', 'active', 12, 4, 'Desarrolladores', 'Desarrolladores', 'Desarrolladores', 130, 72, 'per_sergio_rios', 'per_daniel_quiroz', '130', '21-22', 'OK', 92.6, 'SERGIO ANDRES RIOS PABON', 'OK'),
    ('d805cd09-3c1e-22f5-738e-3c94eda0d97e', 'Evelyn Cardenas', 'Líder Técnico', 'evelyn.cardenas@epayco.com', 'Desarrollo', 'active', 12, 4, 'Desarrolladores', 'Desarrolladores', 'Desarrolladores', 131, 73, 'per_evelyn_cardenas', 'per_daniel_quiroz', '131', '21-22', 'OK', 94, 'EVELYN DAYANA CARDENAS VILLA', 'OK'),
    ('2973d069-2385-bed1-9f3f-2f0c5c268088', 'Cristian Gonzalez', 'Especialista', 'cristian.gonzalez@epayco.com', 'Desarrollo', 'active', 12, 4, 'Desarrolladores', 'Desarrolladores', 'Desarrolladores', 132, 74, 'per_cristian_gonzalez', 'per_daniel_quiroz', '132', '21-22', 'OK', 94.5, 'CRISTIAN DAVID GONZALEZ TORRES', 'OK'),
    ('7366c245-a4e7-2669-68e1-8a4eda610d1c', 'Angel Rangel', 'IOS', 'angel.rangel@epayco.com', 'Desarrollo', 'active', 12, 4, 'Desarrolladores', 'Desarrolladores', 'Desarrolladores', 133, 75, 'per_angel_rangel', 'per_daniel_quiroz', '133', '21-22', 'OK', 92.3, 'ANGEL GABRIEL RANGEL PIÑERO', 'OK'),
    ('c5db3d45-b5e2-be55-62d9-4ede68e2d557', 'Deiby Tovar', 'Líder Técnico', 'deiby.tovar@epayco.com', 'Desarrollo', 'active', 12, 4, 'Desarrolladores', 'Desarrolladores', 'Desarrolladores', 134, 76, 'per_deiby_tovar', 'per_daniel_quiroz', '134', '21-22', 'OK', 92.2, 'DEIBY ISMAEL TOVAR CASTRO', 'OK'),
    ('51471786-95d9-1bcb-201a-6ea46a68d444', 'Luis Asprilla', 'Líder de Seguridad de la Información', 'luis.asprilla@epayco.com', 'Seguridad de la Información', 'active', 13, 3, 'Seguridad de la Información', 'Seguridad de la Información', 'Seguridad de la Información', 135, 1, 'per_luis_asprilla', 'per_juan_david_rua', '135', '23', 'OK', 92.1, 'LUIS ALBERTO ASPRILLA MOSQUERA', 'OK'),
    ('abd5f34c-4e0e-4dce-b835-32bcff477320', 'Hugo Armando Padilla', 'Profesional de Seguridad de la Información', 'hugo.padilla@epayco.com', 'Seguridad de la Información', 'active', 13, 4, 'Seguridad de la Información', 'Seguridad de la Información', 'Seguridad de la Información', 136, 2, 'per_hugo_armando_padilla', 'per_luis_asprilla', '136', '23', 'OK', 96.7, 'HUGO ARMANDO PADILLA ARRIETA', 'OK'),
    ('3fd3396a-6479-7055-cb5b-6b4d1d9ce1d2', 'Isaac Londoño', 'Ciberseguridad', 'isaac.londono@epayco.com', 'Seguridad de la Información', 'active', 13, 4, 'Seguridad de la Información', 'Seguridad de la Información', 'Seguridad de la Información', 137, 3, 'per_isaac_londono', 'per_luis_asprilla', '137', '23', 'OK', 95.8, 'ISAAC LONDOÑO CORTES', 'OK'),
    ('add878f6-1698-c8d0-4642-7f329a65f49c', 'Germán Saavedra', 'Auditor', 'german.saavedra@epayco.com', 'Seguridad de la Información', 'active', 13, 4, 'Seguridad de la Información', 'Seguridad de la Información', 'Seguridad de la Información', 138, 4, 'per_german_saavedra', 'per_luis_asprilla', '138', '23', 'OK', 96.7, 'GERMAN SAAVEDRA RUEDA', 'OK'),
    ('e9c7b24a-f9c3-5b79-28e1-19e9771d7b91', 'Andrés Gómez', 'Gerente de Tecnología', 'andres.gomez@epayco.com', 'Tecnología e Información', 'active', 14, 2, 'Gerencia Tecnología', 'Tecnología e Información', 'Gerencia Tecnología', 139, 1, 'per_andres_gomez', 'per_juan_david_rua', '139', '24', 'OK', 92.3, 'CARLOS ANDRES GOMEZ RAMIREZ', 'OK'),
    ('a87b5dbc-c7a7-73ad-d56c-ef447f543e4d', 'Estiven Escobar', 'Arquitecto de la Nube', 'estiven.escobar@epayco.com', 'Tecnología e Información', 'active', 14, 4, 'Tecnología e Información', 'Tecnología e Información', 'Tecnología e Información', 140, 2, 'per_estiven_escobar', 'per_andres_gomez', '140', '24', 'OK', 93.3, 'ELMER ESTIVEN ESCOBAR PULGARIN', 'OK'),
    ('e12f068b-9517-79f7-054c-c4d13e14b9fe', 'Cristhian Castillo', 'Especialista de Datos', 'cristhian.castillo@epayco.com', 'Tecnología e Información', 'active', 14, 4, 'Tecnología e Información', 'Tecnología e Información', 'Tecnología e Información', 141, 3, 'per_cristhian_castillo', 'per_andres_gomez', '141', '24', 'OK', 93.8, 'CRISTHIAN EDUARDO CASTILLO MENESES', 'OK'),
    ('bfd1e1e0-7895-1228-c134-22dd3f68c082', 'Jhon Fredy Montoya', 'Auxiliar de Tecnología', 'fredy.montoya@epayco.com', 'Tecnología e Información', 'active', 14, 4, 'Tecnología e Información', 'Tecnología e Información', 'Tecnología e Información', 142, 4, 'per_jhon_fredy_montoya', 'per_andres_gomez', '142', '24', 'OK', 96.4, 'JHON FREDY MONTOYA HURTADO', 'OK'),
    ('1c38bbb2-4241-2864-a83e-d1f8c79a9502', 'Johan Giraldo', 'DevOPS', 'johan.giraldo@epayco.com', 'Tecnología e Información', 'active', 14, 4, 'Tecnología e Información', 'Tecnología e Información', 'Tecnología e Información', 143, 5, 'per_johan_giraldo', 'per_andres_gomez', '143', '24', 'OK', 91.8, 'JOHAN SEBASTIAN GIRALDO HURTADO', 'OK'),
    ('326a2461-94dd-fdca-b073-590f2971fb21', 'Santiago Rendón', 'Analista de Datos', 'santiago.rendon@epayco.com', 'Tecnología e Información', 'active', 14, 4, 'Tecnología e Información', 'Tecnología e Información', 'Tecnología e Información', 144, 6, 'per_santiago_rendon', 'per_cristhian_castillo', '144', '24', 'OK', 94.6, 'SANTIAGO RENDON CASTRILLON', 'OK')
),
prepared_people as (
  select
    incoming_people.id::uuid,
    incoming_people.full_name,
    incoming_people.role,
    incoming_people.email,
    departments.id as department_id,
    incoming_people.status,
    incoming_people.department_sort_order,
    incoming_people.hierarchy_order,
    incoming_people.hierarchy_level,
    incoming_people.subarea,
    incoming_people.group_name,
    incoming_people.global_order,
    incoming_people.group_order,
    incoming_people.source_person_id,
    incoming_people.source_parent_id,
    incoming_people.source_row,
    incoming_people.source_pages,
    incoming_people.match_status,
    incoming_people.match_score,
    incoming_people.email_source,
    incoming_people.email_status
  from incoming_people
  left join public.departments departments
    on lower(departments.name) = lower(incoming_people.department_name)
)
insert into public.people (
  id,
  full_name,
  role,
  email,
  department_id,
  manager_id,
  status,
  department_sort_order,
  hierarchy_order,
  hierarchy_level,
  subarea,
  group_name,
  global_order,
  group_order,
  source_person_id,
  source_parent_id,
  source_row,
  source_pages,
  match_status,
  match_score,
  email_source,
  email_status,
  updated_at
)
select
  id,
  full_name,
  role,
  email,
  department_id,
  null,
  status,
  department_sort_order,
  hierarchy_order,
  hierarchy_level,
  subarea,
  group_name,
  global_order,
  group_order,
  source_person_id,
  source_parent_id,
  source_row,
  source_pages,
  match_status,
  match_score,
  email_source,
  email_status,
  now()
from prepared_people
on conflict (email) do update
set full_name = excluded.full_name,
    role = excluded.role,
    department_id = excluded.department_id,
    status = 'active',
    department_sort_order = excluded.department_sort_order,
    hierarchy_order = excluded.hierarchy_order,
    hierarchy_level = excluded.hierarchy_level,
    subarea = excluded.subarea,
    group_name = excluded.group_name,
    global_order = excluded.global_order,
    group_order = excluded.group_order,
    source_person_id = excluded.source_person_id,
    source_parent_id = excluded.source_parent_id,
    source_row = excluded.source_row,
    source_pages = excluded.source_pages,
    match_status = excluded.match_status,
    match_score = excluded.match_score,
    email_source = excluded.email_source,
    email_status = excluded.email_status,
    updated_at = now();

update public.people people
set manager_id = managers.id,
    updated_at = now()
from public.people managers
where people.source_parent_id is not null
  and people.source_parent_id <> ''
  and managers.source_person_id = people.source_parent_id;

update public.people
set manager_id = null,
    updated_at = now()
where source_parent_id is null
   or source_parent_id = '';

update public.people
set status = 'inactive',
    updated_at = now()
where coalesce(source_person_id, '') not in ('per_juan_david_rua', 'per_leidy_gil', 'per_mauricio_gallego', 'per_daniela_ochoa', 'per_william_rua', 'per_jhonatan_giraldo', 'per_andres_moreno', 'per_andres_benavidez', 'per_carolina_amariles', 'per_valentina_de_arco', 'per_juan_esteban_carmona', 'per_angela_mazo', 'per_yuliana_parra', 'per_german_alzate', 'per_carolina_zapata', 'per_xiomara_betancur', 'per_gabriela_urdaneta', 'per_valentina_serna', 'per_santiago_cobaleda', 'per_laura_madrigal', 'per_daniel_valencia', 'per_diana_gonzalez', 'per_ainiri_vargas', 'per_david_marroquin', 'per_katherin_ruiz', 'per_yeimy_espinosa', 'per_sara_calle', 'per_jose_meza', 'per_daniela_areiza', 'per_juan_camilo_acevedo', 'per_sergio_monsalve', 'per_bryan_andrade', 'per_fabian_mesa', 'per_alexandra_rua', 'per_daniela_jaramillo', 'per_nicolas_donoso', 'per_jennifer_hernandez', 'per_luis_felipe_vargas', 'per_andres_felipe_villamil', 'per_luisa_orozco', 'per_wendy_reyes', 'per_alejandra_sanabria', 'per_camila_gallego', 'per_carolina_pulgarin', 'per_alexander_urrego', 'per_estefany_polo', 'per_vanesa_patino', 'per_kelly_daza', 'per_jenny_gomez', 'per_wendy_ortega', 'per_judy_carolina_tovar', 'per_juan_david_henao', 'per_johan_orlas', 'per_andres_julio', 'per_juan_pablo_alvarez', 'per_juan_camilo_morales', 'per_alejandra_villa', 'per_brandon_cervantes', 'per_laura_valeria_de_la_hoz', 'per_nancy_correa', 'per_karen_valbuena', 'per_daniela_castellanos', 'per_julian_tobon', 'per_alexis_herrera', 'per_johana_franco', 'per_jorge_ramirez', 'per_luz_baena', 'per_catherine_aguilar', 'per_valentina_aguilar', 'per_tatiana_giraldo', 'per_jackeline_santafe', 'per_carolina_castano', 'per_alejandra_taborda', 'per_maria_jose_giraldo', 'per_paola_castellanos', 'per_monica_martinez', 'per_daniela_arbelaez', 'per_daniela_gutierrez', 'per_tatiana_torres', 'per_durley_montoya', 'per_claudia_osorno', 'per_monica_ramirez', 'per_juan_diego_vargas', 'per_carolina_euse', 'per_maria_angeles_mejia', 'per_johan_david_restrepo', 'per_luisa_ramirez', 'per_carolina_villamil', 'per_juan_esteban_santana', 'per_mateo_jaramillo', 'per_jesus_gonzalez', 'per_juan_felipe_herrera', 'per_maria_angeles_abello', 'per_eliana_henao', 'per_daniel_quiroz', 'per_paola_alzate', 'per_nixon_cardona', 'per_carlos_moreno', 'per_neida_montoya', 'per_andres_castaneda', 'per_yonny_ospina', 'per_beatriz_monserrate', 'per_jaqueline_orozco', 'per_maria_alejandra_correa', 'per_maria_alejandra_naranjo', 'per_tatiana_betancurth', 'per_olga_cespedes', 'per_valentina_moreno', 'per_laura_perez', 'per_luisa_momphotes', 'per_andres_garcia', 'per_maria_alejandra_nieto', 'per_carlos_duque', 'per_ricardo_saldarriaga', 'per_luis_fuentes', 'per_juan_correa', 'per_jordan_cuadro', 'per_wilfredo_sulbaran', 'per_dorian_lopez', 'per_nelson_lindarte', 'per_oscar_paz', 'per_jose_chaverra', 'per_victor_cortes', 'per_camilo_montoya', 'per_juan_garcia', 'per_nelson_valencia', 'per_brandon_granados', 'per_jonathan_aguirre', 'per_sergio_rios', 'per_evelyn_cardenas', 'per_cristian_gonzalez', 'per_angel_rangel', 'per_deiby_tovar', 'per_luis_asprilla', 'per_hugo_armando_padilla', 'per_isaac_londono', 'per_german_saavedra', 'per_andres_gomez', 'per_estiven_escobar', 'per_cristhian_castillo', 'per_jhon_fredy_montoya', 'per_johan_giraldo', 'per_santiago_rendon')
  and lower(coalesce(email, '')) not in ('juandavid@epayco.com', 'leidy.gil@epayco.com', 'mauricio.bustamante@epayco.com', 'daniela.ochoa@epayco.com', 'william.rua@epayco.com', 'jhonatan.giraldo@epayco.com', 'andres.moreno@epayco.com', 'andres.benavidez@epayco.com', 'carolina.rivera@epayco.com', 'valentina.torres@epayco.com', 'juan.carmona@epayco.com', 'angela.mazo@epayco.com', 'yuliana.parra@epayco.com', 'german.alzate@epayco.com', 'carolina.zapata@epayco.com', 'xiomara.betancur@epayco.com', 'gabriela.urdaneta@epayco.com', 'valentina.serna@epayco.com', 'santiago.cobaleda@epayco.com', 'laura.madrigal@epayco.com', 'daniel.valencia@epayco.com', 'diana.gonzalez@epayco.com', 'ainiri.vargas@epayco.com', 'david.marroquin@epayco.com', 'katherin.ruiz@epayco.com', 'yeimy.espinosa@epayco.com', 'melissa.calle@epayco.com', 'jose.meza@epayco.com', 'daniela.areiza@epayco.com', 'camilo.acevedo@epayco.com', 'sergio.monsalve@epayco.com', 'bryan.andrade@epayco.com', 'fabian.mesa@epayco.com', 'alexandra.rua@epayco.com', 'daniela.jaramillo@epayco.com', 'nicolas.donoso@epayco.com', 'jennifer.hernandez@epayco.com', 'luis.vargas@epayco.com', 'andres.villamil@epayco.com', 'luisa.orozco@epayco.com', 'wendy.reyes@epayco.com', 'alejandra.sanabria@epayco.com', 'camila.gallego@epayco.com', 'carolina.pulgarin@epayco.com', 'alexander.urrego@epayco.com', 'estefany.polo@epayco.com', 'vanesa.patino@epayco.com', 'kelly.daza@epayco.com', 'jenny.gomez@epayco.com', 'wendy.ortega@epayco.com', 'carolina.tovar@epayco.com', 'juan.henao@epayco.com', 'johan.orlas@epayco.com', 'andres.julio@epayco.com', 'juan.alvarez@epayco.com', 'camilo.morales@epayco.com', 'alejandra.villa@epayco.com', 'brandon.cervantes@epayco.com', 'valeria.londono@epayco.com', 'nancy.correa@epayco.com', 'karen.valbuena@epayco.com', 'daniela.castellanos@epayco.com', 'julian.tobon@epayco.com', 'alexis.herrera@epayco.com', 'johana.franco@epayco.com', 'jorge.ramirez@epayco.com', 'luz.baena@epayco.com', 'caguilar@epayco.com', 'valentina.aguilar@epayco.com', 'tatiana.giraldo@epayco.com', 'jackeline.santafe@epayco.com', 'carolina.castano@epayco.com', 'alejandra.taborda@epayco.com', 'maria.giraldo@epayco.com', 'paola.castellanos@epayco.com', 'monica.martinez@epayco.com', 'daniela.arbelaez@epayco.com', 'daniela.gutierrez@epayco.com', 'leidy.torres@epayco.com', 'durley.montoya@epayco.com', 'claudia.osorno@epayco.com', 'monica.ramirez@epayco.com', 'diego.vargas@epayco.com', 'carolina.euse@epayco.com', 'maria.mejia@epayco.com', 'johan.restrepo@epayco.com', 'luisa.ramirez@epayco.com', 'carolina.villamil@epayco.com', 'juan.santana@epayco.com', 'mateo.jaramillog@epayco.com', 'jesus.gonzalez@epayco.com', 'felipe.herrera@epayco.com', 'maria.abello@epayco.com', 'eliana.henao@epayco.com', 'daniel.quiroz@epayco.com', 'paola.alzate@epayco.com', 'nixon.cardona@epayco.com', 'carlos.moreno@epayco.com', 'neida.montoya@epayco.com', 'andres.castaneda@epayco.com', 'yonny.ospina@epayco.com', 'maria.monserrate@epayco.com', 'jaqueline.orozco@epayco.com', 'maria.correa@epayco.com', 'maria.naranjo@epayco.com', 'tatiana.betancurth@epayco.com', 'olga.cespedes@epayco.com', 'valentina.moreno@epayco.com', 'laura.perez@epayco.com', 'luisa.momphotes@epayco.com', 'andres.garcia@epayco.com', 'alejandra.nieto@epayco.com', 'carlos.duque@epayco.com', 'ricardo.saldarriaga@epayco.com', 'luis.fuentes@epayco.com', 'juan.correa@epayco.com', 'jordan.cuadro@epayco.com', 'wilfredo.sulbaran@epayco.com', 'dorian.lopez@epayco.com', 'nelson.lindarte@epayco.com', 'oscar.paz@epayco.com', 'jose.chaverra@epayco.com', 'victor.cortes@epayco.com', 'camilo.montoya@epayco.com', 'juan.garcia@epayco.com', 'nelson.valencia@epayco.com', 'sebastian.granados@epayco.com', 'jaguirre@epayco.com', 'sergio.rios@epayco.com', 'evelyn.cardenas@epayco.com', 'cristian.gonzalez@epayco.com', 'angel.rangel@epayco.com', 'deiby.tovar@epayco.com', 'luis.asprilla@epayco.com', 'hugo.padilla@epayco.com', 'isaac.londono@epayco.com', 'german.saavedra@epayco.com', 'andres.gomez@epayco.com', 'estiven.escobar@epayco.com', 'cristhian.castillo@epayco.com', 'fredy.montoya@epayco.com', 'johan.giraldo@epayco.com', 'santiago.rendon@epayco.com');

insert into public.change_history (actor, action, target, after_data)
values (
  'codex',
  'Carga maestra ePayco',
  '143 personas / 14 departamentos',
  jsonb_build_object('source', 'ORGANIGRAMA_EPAYCO_MAESTRO_COMPLETO_FINAL.xlsx')
);

commit;
